apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
# ReplicationSet specification
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    # Container specification
    spec:
      containers:
        - name: app-site
          image: kubedevio/nginx-color:blue
          ports:
            - containerPort: 80